### ISSUE TITLE
api_protocol seems to be ignored

### ISSUE THREAD

**Issue by alzedd** [profclems/glab#270]
It seems that I can't se `api_protocol` for a custom gitlab install
**Description**

This is my minimal config
```yaml
hosts:
    gitlab.self.hosted.address: # omitted actual URL
        token: xxxxxxx # omitted actual token
        api_protocol: http # found this setting in sources, but it seems to be ignored
```

**Expected Behavior**

My custom gitlab URL should use the defined `api_protocol` (eg: http://gitlab.self.hosted.address)

**Actual Behavior**

Every Api Call is done in HTTPS (eg: https://gitlab.self.hosted.address) getting an 'untrusted certificates' error.

**Steps to Reproduce**

1.  `glab config set token xxxxxx --host=gitlab.self.hosted.address`
2. `glab mr list`
3. Get the error, if your gitlab instance does not support HTTPS

**Your Environment**

* Version used: ❯ glab 1.11.0-pre2 ()

* Operating System and version: Mac Os Catalina (10.15.7)
