### ISSUE TITLE
Support multiple authentication states (Different GitLab instances)

### ISSUE THREAD

**Issue by fermentfan** [profclems/glab#377]
Forgive me if I am missing that feature, but I tried the tool and read the docs and it seems like you don't support this use case. If that's not the case, please close this issue.

**Describe the feature or problem you'd like to solve**
I work with multiple GitLab instances daily. At the moment I can only login to one instance at a time and will have to switch the authentication state when I want to switch to another instance. Working around this would be kinda tedious (using environment variables or overriding with the provided switches), but I think separate states in the tool would be best (a la kubectl).

**Propose a Solution**
Save every hostname and access token in a list of auth states and let me manage every login state with the auth command. Additional logins should always be possible. glab should also look into the remote hostname of the active (pwd) GIT repository to choose which GitLab instance to call before executing the command.

**Additional context**

**Comment by profclems** [comment]
`glab` by default supports multiple GitLab instances. You can run `glab auth login` several times to authenticate several GitLab Instances. `glab` automatically detects the authenticated hostname from the remotes available in the working git directory. So you don't need to switch manually as `glab` does that. If none of the remotes has an authenticated hostname, you would have to run `glab auth login` to authenticate the hostname.

If you have multiple instances authenticated, your config (`$HOME/.config/glab-cli/config.yml`) looks like this:
```YAML
...
...
hosts:
    gitlab.com:
        # What protocol to use to access the api endpoint. Supported values: http, https
        api_protocol: https
        # Your GitLab access token. Get an access token at https://gitlab.com/profile/personal_access_tokens
        token: ********
        git_protocol: ssh
        user: profclems

    gitlab.gnome.org:
        api_protocol: ssh
        token: ********
        git_protocol: ssh
        user: profclems

    another.host:
        ...
        ...

    yet.another.host:
        ...
        ...
```

**Must Know:**
If `glab` is run from a git repository, it looks through the git remotes available and checks if any of them is authenticated. 
It is extremely rare to have multiple authenticated hosts in a single repository but if that happens, `glab` gives priority to the remotes nicknames in this order `upstream > gitlab > origin`. 
If there are multiple remotes pointing to the same hosts, like:
```sh
$ git remote -v
origin  git@gitlab.com:zemzale/glab.git (fetch)
origin  git@gitlab.com:zemzale/glab.git (push)
upstream  git@gitlab.com:profclems/glab.git (fetch)
upstream  git@gitlab.com:profclems/glab.git (push)
```
`glab` will merge them into a single host since they are both pointing to `gitlab.com` and ask the user at first run, which of the repos to use and it caches it in the git config:
```sh
? Which should be the base repository (used for e.g. querying issues) for this directory?
> profclems/glab
  zemzale/glab
```
This happens especially with forks
