### ISSUE TITLE
Can't checkout branch on gitlab.alpinelinux.org

### ISSUE THREAD

**Issue by maxice8** [profclems/glab#383]
**Description**
![image](https://user-images.githubusercontent.com/30738253/102841775-51dd6380-43e4-11eb-8e8d-fc7c6a556a37.png)

![image](https://user-images.githubusercontent.com/30738253/102841506-d4b1ee80-43e3-11eb-97b2-802e390a1430.png)

**Expected Behavior vs Actual Behavior**
Checked out branch from merge request

**Steps to Reproduce**
1. Register gitlab.alpinelinux.org with a personal access token
2. try to checkout a branch

**Logs**
In screenshot

**Your Environment**

* Version used: glab version 1.12.1-82-g0c3ff7e (2020-12-21)
* Operating System and version: Fedora SilverBlue 33

**Comment by maxice8** [comment]
Oh derp, if I pass -R alpine/aports it reverts back to gitlab.com even though .glab-cli has host: gitlab.alpinelinux.org

**Comment by profclems** [comment]
This is kinda minor limitation with `glab`. When using the repo override (`-R`), glab uses gitlab.com if repo host is not specified together with the repo.

This should work:
```sh
glab mr checkout 15974 -R gitlab.alpinelinux.org/alpine/aports
```

**Comment by maxice8** [comment]
Understandable although not very ergonomic

**Comment by profclems** [comment]
We will fix that for sure. I have added it to the project backlog. Maybe we could fix that and add to v1.13.0 release

**Comment by maxice8** [comment]
thanks

**Comment by solidnerd** [comment]
@profclems It's mostly specifying a base URL for your glab or we could have a similar feature like `docker context` or `kubectl context` where you can specify in which config context you are currently. 

Default would be gitlab.com but as a user, I could define my own context for alpine as an example:

```yaml
apiVersion: alpha/v1
instances:
- alpine:
    url: gitlab.alpinelinux.org
- gitlab-com:
    url: gitlab.com
contexts:
- context:
    instance: alpine
    user: alpine
  name: alpine
- context:
    instance: gitlab-com
    user: gitlab-user
  name: default
users:
- name: alpine-user
  user:
    token: "abc1234"
- name: gitlab-user
  user:
    token: "foobar"
```

Here is something that comes to my mind.
