### ISSUE TITLE
Can't merge a Merge Request if I am in detached HEAD state

### ISSUE THREAD

**Issue by jume-dev** [profclems/glab#735]
**Description**
So, I am running glab in a gitlab-ci pipeline with the goal to create a MR from development to main and automerge it, if the pipeline succeeds.

As I run in an MR pipeline, the git state is a detached HEAD. I try to execute `glab mr merge <id>` with an correct ID and get the error:
`could not determine current branch: git: not on any branch`.

Creating the MR with `glab mr create -b main -s development -y -t test -d ""` did work however

**Expected Behavior vs Actual Behavior**
It should not give me the error as I am not interacting with the current git state anyway

**Possible Fix**
Maybe mr merge can be refactored to use whatever mr create is doing.

**Your Environment**
I am trying to get this pipeline to work:
```
  stage: release
  image: alpine
  needs: []
  variables:
    DESCRIPTION: test
    SOURCE_BRANCH: $CI_DEFAULT_BRANCH
    TARGET_BRANCH: main
    TITLE: '[Dependency Update] test release'
    TOKEN: $TEST_PAT
  before_script:
    - 'echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories'
    - apk add --no-cache glab@edge
  script:
    - echo $TOKEN | glab auth login --stdin
    - glab mr create -b $TARGET_BRANCH -s $SOURCE_BRANCH -y -t "$TITLE" -d "$DESCRIPTION"
    - export MR_ID=$(glab mr ls -s $SOURCE_BRANCH -t $TARGET_BRANCH | grep ! | awk '{print substr($1,2);}')
    - glab mr merge $MR_ID -R osp-cl/movex/customer-service-2.0/queries/read-config
```
