### ISSUE TITLE
Using Alternate Ports for GIT/API Generates "none of the git remotes configured ..." Error

### ISSUE THREAD

**Issue by esorton** [profclems/glab#755]
Following instructions in #738, I configured glab to access our self-hosted GitLab installation.  We use alternate ports for both SSH access to the repository and HTTPS access to the web/API.  `.config/glab-cli/config.yml` contains (port and hostnames changed):

```
example.host.com:12388:
   git_protocol: ssh
   api_host: example.host.com:12399
   api_protocol: https
   token: **********
```

Executing with the --repo argument works:

```
% glab issue list --repo example.host.com:12388/path/repo
Showing 15 open issues in path/repo that match your search (Page 1)
... issues listed ...
```

However, if I execute the above command without --repo in the repository directory, the command fails:

```
% glab issue list
none of the git remotes configured for this repository points to a known GitLab host. Please use `glab auth login` to authenticate and configure a new host for glab
```

The remotes for the repository are configured as:

```
% git remove -v
origin  ssh://git@host.example.com:12388/path/repo.git (fetch)
origin  ssh://git@host.example.com:12388/path/repo.git (push)
```

Error is from `commands/cmdutils/remote_resolver.go:92`

Host is running debian.  Downloaded and installed latest glab deb from GitHub.

```
% glab --version
glab version 1.17.0 (2021-05-14)
```

**Comment by profclems** [comment]
Hi @esorton , thanks for reporting the issue. 

Does it work when the main host entry in the config does not contain a port number?

Kindly modify the config to see if it works:


```yaml
example.host.com:
   git_protocol: ssh
   api_host: example.host.com:12399
   api_protocol: https
   token: **********
```

Or you can replicate the host config to have multiple host entries with one containing the port number:

```yaml
example.host.com:
   git_protocol: ssh
   api_host: example.host.com:12399
   api_protocol: https
   token: **********

example.host.com:12399:
   git_protocol: ssh
   api_host: example.host.com:12399
   api_protocol: https
   token: **********
```

Let me know which one works... Thanks
